### PR TITLE
release: 1.0.0

### PR DESCRIPTION
**Pull request by curbengh**

### CODE REVIEW

**Comment by curbengh** [comment]
Pending [hexo-bunyan@2](https://github.com/hexojs/hexo-bunyan/pull/10).

**Comment by curbengh** [comment]
Pending https://github.com/hexojs/hexo-bunyan/pull/12

**Comment by curbengh** [comment]
https://www.npmjs.com/package/hexo-bunyan/v/2.0.0 released, pending dependabot.

**Comment by SukkaW** [comment]
@curbengh hexo-bunyan@2 is now merged into hexo-log.

**Comment by curbengh** [comment]
Ready

**Comment by curbengh** [comment]
https://www.npmjs.com/package/hexo-log/v/1.0.0

**Pull request merged**
